controllers/nginx-deployment.yaml  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oncall-issue-filer
  labels:
    app: oncall-issue-filer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oncall-issue-filer
  template:
    metadata:
      labels:
        app: oncall-issue-filer
    spec:
      containers:
      - name: envars-test-container
        image: quay.io/philips/oncall-issue-filer
        env:
        - name: ONCALL_ISSUE_FILER_GITHUB_API_KEY
          valueFrom:
            secretKeyRef:
              name: oncall-issue-filer
              key: github-api-key
        - ONCALL_ISSUE_FILER_GITHUB_REPO
          valueFrom:
            secretKeyRef:
              name: oncall-issue-filer
              key: github-repo
        - name: ONCALL_ISSUE_FILER_OPSGENIE_API_KEY
          valueFrom:
            secretKeyRef:
              name: oncall-issue-filer
              key: opsgenie-api-key
